# idGuru.spec — PyInstaller build specification
# Run with: pyinstaller idGuru.spec --clean

block_cipher = None

a = Analysis(
    ['idguru_main.py'],
    pathex=[],
    binaries=[
        (r'C:\ffmpeg\bin\ffmpeg.exe', '.'),
        (r'C:\ffmpeg\bin\ffprobe.exe', '.'),
    ],
    datas=[],
    hiddenimports=[
        'anthropic',
        'flask',
        'flask.templating',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageEnhance',
        'pystray',
        'pystray._win32',
        'rich',
        'rich.console',
        'rich.progress',
        'rich.table',
        'sqlite3',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'rawpy',
        'concurrent.futures',
        'threading',
        'queue',
        'webbrowser',
        'json',
        'hashlib',
        'base64',
        'argparse',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='idGuru',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
